GET http://localhost:8081/restaurants

###
POST http://localhost:8081/restaurants
Content-Type: application/json

{
  "name": "Rest 1",
  "address": "Addr 1",
  "phone": "1234567890"
}

###

GET http://localhost:8081/restaurants/122
